version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9070:9070"
      - "9071:9071"
    environment:
      MINIO_ROOT_USER: minio          #管理后台用户名
      MINIO_ROOT_PASSWORD: Ljy2002319 #管理后台密码，最小8个字符
    volumes:
      - /home/minio/data:/data
      - /etc/localtime:/etc/localtime
    network_mode: bridge
    command: server  --address :9071 --console-address :9070 /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9071/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"
    network_mode: bridge
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
      - "9456:9456"
    network_mode: bridge
    volumes:
      - /home/develop/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/develop/nginx/log:/var/log/nginx

