// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	favorite "github.com/Skyenought/tiktokbackend/cmd/video/api/internal/handler/favorite"
	publish "github.com/Skyenought/tiktokbackend/cmd/video/api/internal/handler/publish"
	"github.com/Skyenought/tiktokbackend/cmd/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: publish.PublishlistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: publish.PublishActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: FeedHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: favorite.FavoriteVideoListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: favorite.FavoriteActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/favorite"),
	)
}
