// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "github.com/Skyenought/tiktokbackend/cmd/user/api/internal/handler/message"
	relation "github.com/Skyenought/tiktokbackend/cmd/user/api/internal/handler/relation"
	user "github.com/Skyenought/tiktokbackend/cmd/user/api/internal/handler/user"
	"github.com/Skyenought/tiktokbackend/cmd/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: relation.FollowActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: relation.UserfollowlistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: relation.UserfanslistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: relation.UserfriendlistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/relation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: message.MsgActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: message.MsgChatListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/message"),
	)
}
