// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "github.com/Skyenought/tiktokbackend/cmd/comment/api/internal/handler/comment"
	"github.com/Skyenought/tiktokbackend/cmd/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: comment.CommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: comment.CommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/comment"),
	)
}
