// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"github.com/Skyenought/tiktokbackend/cmd/comment/rpc/commentrpc"
	"github.com/Skyenought/tiktokbackend/cmd/comment/rpc/internal/logic"
	"github.com/Skyenought/tiktokbackend/cmd/comment/rpc/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	commentrpc.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CommentAction(ctx context.Context, in *commentrpc.CommentActionReq) (*commentrpc.CommentActionResp, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *CommentServiceServer) CommentList(ctx context.Context, in *commentrpc.CommentListReq) (*commentrpc.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
